<?php
/**
 * Created by PhpStorm.
 * User: Sasha
 * Date: 29.01.2019
 * Time: 10:41
 */

namespace App\Admin;

use FOS\UserBundle\Model\UserManagerInterface;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class BaseAdmin extends AbstractAdmin
{
    /** @var UserManagerInterface */
    private $userManager;

    /** @var UserPasswordEncoderInterface */
    private $encoder;

    public function __construct(string $code, string $class, string $baseControllerName,
                                UserManagerInterface $userManager,
                                UserPasswordEncoderInterface $encoder)
    {
        parent::__construct($code, $class, $baseControllerName);
        $this->userManager = $userManager;
        $this->encoder = $encoder;
    }

//    public function preUpdate($user)
//    {
//        $encoded = $this->encoder->encodePassword($user,$user->getPlainPassword());
//        $user->setPassword($encoded);
//        $this->userManager->updateCanonicalFields($user);
//        $this->userManager->updatePassword($user);
//        parent::preUpdate($user); // TODO: Change the autogenerated stub
//    }

    public function prePersist($object)
    {
        $plainPassword = $object->getPlainPassword();
        $encoded = $this->encoder->encodePassword($object, $plainPassword);

        $object->setPassword($encoded);
    }

    protected function configureFormFields(FormMapper $formMapper)
    {
        $container = $this->getConfigurationPool()->getContainer();
        $roles = $container->getParameter('security.role_hierarchy.roles');

        $rolesChoices = self::flattenRoles($roles);

        $formMapper
            ->with('General')
            ->add('username')
            ->add('plainPassword', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options' => array('label' => 'Password'),
                'second_options' => array('label' => 'Password confirmation')
            ))
            ->add('email')
            ->add('enabled', null, array('required' => false))
            ->add('roles', ChoiceType::class, array(
//                'data'  => $rolesChoices,
                'choices' => ['ROLE_SUPER_ADMIN' => 'ROLE_SUPER_ADMIN', 'ROLE_ADMIN' => 'ROLE_ADMIN', 'ROLE_USER' => 'ROLE_USER'],
                'multiple' => true,
                'required' => false
            ))
            //->add('plainPassword', 'text', array('required' => false))
            ->end();
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('id')
            ->add('username')
            ->add('enabled')
            ->add('email');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('username')
            ->add('email')
            ->add('enabled', null, array('editable' => true))
            ->add('createdAt');

    }

    /**
     * @param string $baseRouteName
     */
    public function setBaseRouteName(string $baseRouteName): void
    {
        $this->baseRouteName = $baseRouteName;
    }

    protected static function flattenRoles($rolesHierarchy)
    {
        $flatRoles = array();
        foreach ($rolesHierarchy as $roles) {

            if (empty($roles)) {
                continue;
            }

            foreach ($roles as $role) {
                if (!isset($flatRoles[$role])) {
                    $flatRoles[$role] = $role;
                }
            }
        }

        return $flatRoles;
    }
}
