version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: symfony4-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=user
        - MYSQL_PASSWORD=123
      ports:
        - "8003:3306"
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

    webserver:
      image: nginx:alpine
      restart: always
      container_name: symfony4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./BackServer/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
       - php-fpm
      ports:
       - "8001:80"

    php-fpm:
      build: 
        context: ./BackServer
        dockerfile: docker/php.docker
      container_name: symfony4-php-fpm
      working_dir: /application/FrontServer
      volumes:
        - .:/application
        - ./BackServer/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      depends_on:
        - rabbitmq
        - mysql
      ports:
        - "8000:80"

    rabbitmq:
      image: rabbitmq:3.7.5-management
      # image: bitnami/rabbitmq:latest
      working_dir: /application/FrontServer
      # build:
      #     context: ./Symfony
      #     dockerfile: docker/rabbitMQ.docker
      hostname: rabbit-mq
      container_name: symfony4-rabbit-mq
      volumes:
        - .:/application
      ports:
        - '15672:15672'
        - '5672:5672'
      environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"