version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: docker-symfony4-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=user
        - MYSQL_PASSWORD=123
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: docker-symfony4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./LaravelServer/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
       - php-fpm
      ports:
       - "8001:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-symfony4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./LaravelServer/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    rabbitmq:
      image: rabbitmq:3.7.5-management
      # image: bitnami/rabbitmq:latest
      working_dir: /application
      # build:
      #     context: ./Symfony
      #     dockerfile: docker/rabbitMQ.docker
      hostname: rabbit-mq
      container_name: docker-symfony4-rabbit-mq
      volumes:
        - .:/application
      ports:
        - '15672:15672'
        - '5672:5672'
      environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"